### ISSUE TITLE
Update the documentation and README.md upon publication

### ISSUE THREAD

**Issue by evancofer** [kosticlab/aether#1]
Upon publication, add the following to documentation/docs/frequently_asked_questions.md. Remember that BibTex uses a 3-letter name for publication months.

> \### How should I cite this website/software/paper?
You should cite the paper, as this web page and software are supplementary materials for the paper.
We have provided a BibTex citation for the paper below.
>
>\```TeX
\@​article{TitleWithoutSpacesInIt,
    author = {Luber, Jacob M. and Tierney, Braden T. and Cofer, Evan M. and Patel, Chirag J. and Kostic, Aleksandar D.},
    title = {  },
    month = {jan},
    year = {  },
    doi = {  },
    publisher = {  },
    URL = {\url{  }},
    journal = { },
}
\```
>
>\---

Additionally, change the line to the top-level README.md about the forthcoming publication to something similar to the following:
> For a more in-depth discussion of Cumulonimble, consider reading our [paper in JournalName](link to publicationpage)

Lastly, we will have to fill in values for the meta tags in documentation/template/main.html. Currently, the empty tags are commented out. Upon publication, we will just have to fill these in and un-comment them. More info on the meta tags can be found [here](http://blog.reallywow.com/archives/123/) or [here](https://www.monperrus.net/martin/accurate+bibliographic+metadata+and+google+scholar).

Once the docs have been changed, we will have to re-deploy them. We are currently using MkDocs and GitHub Pages to host documentation. More information about this process can be found [here](http://www.mkdocs.org/).

**Comment by jacobluber** [comment]
Link added.
